### ISSUE TITLE
Detail Fix from Sprint 1.0

### ISSUE THREAD

**Issue by Medi0202** [sangyong-99/Team-ARTX-SelfAffirmation#26]
## 📌  Description

스프린트 1.0에서 놓친 디테일 작업 구현

## 📝  To-do

- [ ] 배경 전환 속도 빠르고 최적화된다
- [ ] 테마 적용이(글씨 색) 부드럽게 바뀐다
- [ ] 카드 넘어갈 때 햅틱 반응이 있다
